### ISSUE TITLE
Bad 404 Error Page

### ISSUE THREAD

**Issue by DavidAylaian** [ftf841/Applied-Visuals-Site#1]
Very self-explanatory. Right now appliedvisuals.tk/hdhwgdue displays a "coming soon!" page, yet I certainly don't think we're planning on making a separate page for every single 404!

I think that the domain owner (@ftf841) is the only one who can resolve this.

**Comment by ftf841** [comment]
any random /asdfagfjhaksfd redirects to the home page. It's because of the
way the domain is forwarded.

**Comment by DavidAylaian** [comment]
Closed because this issue has to do with our server and not our code GitHub

**Comment by DavidAylaian** [comment]
Fixed in 0375d4db79f2833f74ad9c89b630d9a535072a99
