### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by DavidAylaian** [ftf841/Applied-Visuals-Site#4]
Make a [footer](http://materializecss.com/footer.html) for the page.

**Comment by ftf841** [comment]
we have no content

**Comment by DavidAylaian** [comment]
@ftf841 that's irrelevant. The footer will be our copyright notice.

**Comment by ftf841** [comment]
kkk

**Comment by DavidAylaian** [comment]
Resolved by 1d1f7f933f478bd7cb9c62399021886ae8e9f32d
