### ISSUE TITLE
Works Dropdown position

### ISSUE THREAD

**Issue by ftf841** [ftf841/Applied-Visuals-Site#6]
The position of the dropdown for the works page is not underneath the button,.

**Comment by DavidAylaian** [comment]
I'd also like to note that we need to stop using htmlpreview.github.io because it messes up badly.

**Comment by DavidAylaian** [comment]
I removed the dropdown in 2206a6db983cc3bf7f9f8f062eb8c0f56af204e2. Fix it yourself or get rid of it, as this feels like a bad idea because we don't have any works right now, let alone enough for 2 pages!

**Comment by ftf841** [comment]
we were going to put our art that's what Andrew wanted. I'm going to report
you for not doing what the boss wanted xd

**Comment by DavidAylaian** [comment]
Tell Andrew that he's a bad leader because this is about websites not art xd

**Comment by ftf841** [comment]
kkk

**Comment by ftf841** [comment]
from andrew:
"ok"
